#pragma once

#define SIMDTEXT_VERSION_MAJOR 0
#define SIMDTEXT_VERSION_MINOR 2
#define SIMDTEXT_VERSION_PATCH 0
#define SIMDTEXT_VERSION_STRING "0.2.0"
#define SIMDTEXT_VERSION SIMDTEXT_VERSION_STRING
